### ISSUE TITLE
fatal error: Windows.h

### ISSUE THREAD

**Issue by recoverycount** [ReddyyZ/GhostShell#7]
Hello i cant compile in kali 2020 i use the command:
x86_64-w64-mingw32-gcc -o main.exe main.c -l psapi -static

and i got the following error
In file included from main.c:1:
main.h:3:10: fatal error: Windows.h: No such file or directory
    3 | #include <Windows.h>
googling i read than this only work compiling in windows?

**Comment by padaxinops** [comment]
In Kali 2020, Mingw not has `#include <Windows.h>`,  you can try #include <windows.h>

**Comment by ReddyyZ** [comment]
It worked?
